"""
Model gateway abstraction and adapters.

Architecture:
- ``ModelGateway`` — abstract base class defining the interface.
- ``OllamaGateway`` — production adapter that calls a local Ollama endpoint.
- ``DryRunGateway`` — deterministic mock adapter for ``--dry-run`` mode.

The gateway always returns an :class:`AnalysisResult` which bundles the
validated payload (or fallback) with provenance metadata so callers never
need to inspect raw model strings directly.
"""

from __future__ import annotations

import abc
import os
import time
from dataclasses import dataclass, field
from typing import Optional

import requests

from .parser import ParseFailureKind, ParseResult, build_fallback_analysis, parse_and_validate
from .schema import ANALYSIS_RESPONSE_SCHEMA  # noqa: F401 – re-exported for convenience


# ---------------------------------------------------------------------------
# Result type
# ---------------------------------------------------------------------------


@dataclass
class AnalysisResult:
    """Encapsulates the outcome of a single analysis request.

    Attributes:
        payload:        Validated analysis dict (may be a fallback if ``is_fallback``).
        ok:             True when the model returned a valid structured response.
        is_fallback:    True when ``payload`` was generated by the fallback path.
        failure:        Parse failure classification (when ``ok`` is False).
        error_detail:   Human-readable failure reason (when ``ok`` is False).
        latency_ms:     Round-trip time to the model in milliseconds.
        model_name:     Name of the model used.
        changeset_fields: Ready-to-merge dict of ChangeSet enrichment keys.
    """

    payload: dict
    ok: bool
    is_fallback: bool = False
    failure: Optional[ParseFailureKind] = None
    error_detail: str = ""
    latency_ms: float = 0.0
    model_name: str = ""
    changeset_fields: dict = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Abstract base
# ---------------------------------------------------------------------------


class ModelGateway(abc.ABC):
    """Abstract model gateway.  All adapters must implement ``analyse``."""

    @abc.abstractmethod
    def analyse(self, raw_event: str) -> AnalysisResult:
        """Analyse a raw event string and return a structured :class:`AnalysisResult`.

        Implementations must never raise — failures should be captured in the
        returned :class:`AnalysisResult` with ``ok=False`` and a populated
        ``failure`` / ``error_detail``.

        Args:
            raw_event: The raw event text to analyse.

        Returns:
            An :class:`AnalysisResult`.
        """


# ---------------------------------------------------------------------------
# Prompt builder (shared)
# ---------------------------------------------------------------------------

_JSON_PROMPT_TEMPLATE = """\
You are an ambient background AI assistant running autonomously on a home server.
Review the following single system event log entry and respond with a JSON object only.

Event: {event}

Respond with a JSON object that has exactly these fields:
- "severity": one of "High", "Medium", or "Low"
- "confidence": a number between 0.0 and 1.0 reflecting your certainty
- "summary": a plain-English summary of what happened (one or two sentences)
- "recommendation": a single actionable sentence for the operator
- "reason_codes": an array of one or more of these tags:
  "SECURITY_ALERT", "NETWORK_ANOMALY", "RESOURCE_PRESSURE",
  "DEPLOYMENT_EVENT", "EXTERNAL_EVENT", "ROUTINE_ACTIVITY", "UNKNOWN"
- "source_event": the original event text (copy it verbatim)

Return only the JSON object. Do not include any explanation or markdown fences.
"""


def _build_structured_prompt(raw_event: str) -> str:
    return _JSON_PROMPT_TEMPLATE.format(event=raw_event)


# ---------------------------------------------------------------------------
# Ollama adapter
# ---------------------------------------------------------------------------


class OllamaGateway(ModelGateway):
    """Model gateway that sends requests to a local Ollama instance.

    Args:
        url:        Ollama generate endpoint (default: ``OLLAMA_URL`` env or
                    ``http://localhost:11434/api/generate``).
        model_name: Model to use (default: ``OLLAMA_MODEL`` env or ``qwen3.5:4b``).
        timeout:    HTTP timeout in seconds (default: 120, allows cold model load).
    """

    DEFAULT_URL = "http://localhost:11434/api/generate"
    DEFAULT_MODEL = "qwen3.5:4b"

    def __init__(
        self,
        url: Optional[str] = None,
        model_name: Optional[str] = None,
        timeout: int = 120,
    ) -> None:
        self.url = url or os.getenv("OLLAMA_URL", self.DEFAULT_URL)
        self.model_name = model_name or os.getenv("OLLAMA_MODEL", self.DEFAULT_MODEL)
        self.timeout = timeout

    def analyse(self, raw_event: str) -> AnalysisResult:
        """Send ``raw_event`` to Ollama and return a structured :class:`AnalysisResult`."""
        prompt = _build_structured_prompt(raw_event)
        start = time.monotonic()
        try:
            response = requests.post(
                self.url,
                json={"model": self.model_name, "prompt": prompt, "stream": False},
                timeout=self.timeout,
            )
            response.raise_for_status()
            raw_output = response.json().get("response", "").strip()
        except requests.RequestException as exc:
            latency_ms = (time.monotonic() - start) * 1000
            fallback = build_fallback_analysis(raw_event, ParseFailureKind.UNKNOWN)
            return AnalysisResult(
                payload=fallback,
                ok=False,
                is_fallback=True,
                failure=ParseFailureKind.UNKNOWN,
                error_detail=str(exc),
                latency_ms=latency_ms,
                model_name=self.model_name,
                changeset_fields=_changeset_from(fallback),
            )

        latency_ms = (time.monotonic() - start) * 1000
        return _result_from_parse(parse_and_validate(raw_output), raw_event, latency_ms, self.model_name)


# ---------------------------------------------------------------------------
# Dry-run mock adapter
# ---------------------------------------------------------------------------


class DryRunGateway(ModelGateway):
    """Deterministic mock gateway for ``--dry-run`` mode.

    No network calls are made.  The response is built from keyword heuristics
    on the event text, matching the behaviour of the original
    ``generate_mock_analysis`` helper.
    """

    MODEL_NAME = "dry-run-mock"

    def analyse(self, raw_event: str) -> AnalysisResult:
        """Return a mock :class:`AnalysisResult` without calling any model."""
        start = time.monotonic()
        fallback = build_fallback_analysis(raw_event, ParseFailureKind.UNKNOWN)
        # Override reason_codes for dry-run distinction.
        reason_codes = [
            c for c in fallback["reason_codes"] if c != "PARSE_FALLBACK"
        ]
        reason_codes.append("DRY_RUN_MOCK")
        fallback["reason_codes"] = reason_codes
        fallback["confidence"] = 0.5
        latency_ms = (time.monotonic() - start) * 1000
        return AnalysisResult(
            payload=fallback,
            ok=True,
            is_fallback=False,
            latency_ms=latency_ms,
            model_name=self.MODEL_NAME,
            changeset_fields=_changeset_from(fallback),
        )


# ---------------------------------------------------------------------------
# Factory helper
# ---------------------------------------------------------------------------


def make_gateway(dry_run: bool = False, **kwargs) -> ModelGateway:
    """Return the appropriate :class:`ModelGateway` implementation.

    Args:
        dry_run: When ``True``, return a :class:`DryRunGateway`.
        **kwargs: Forwarded to :class:`OllamaGateway` when ``dry_run`` is False.

    Returns:
        A :class:`ModelGateway` instance.
    """
    if dry_run:
        return DryRunGateway()
    return OllamaGateway(**kwargs)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _changeset_from(payload: dict) -> dict:
    from .schema import map_to_changeset_fields
    return map_to_changeset_fields(payload)


def _result_from_parse(
    parse_result: ParseResult,
    raw_event: str,
    latency_ms: float,
    model_name: str,
) -> AnalysisResult:
    if parse_result.ok:
        return AnalysisResult(
            payload=parse_result.payload,
            ok=True,
            latency_ms=latency_ms,
            model_name=model_name,
            changeset_fields=parse_result.changeset_fields,
        )
    fallback = build_fallback_analysis(raw_event, parse_result.failure)
    return AnalysisResult(
        payload=fallback,
        ok=False,
        is_fallback=True,
        failure=parse_result.failure,
        error_detail=parse_result.error_detail,
        latency_ms=latency_ms,
        model_name=model_name,
        changeset_fields=_changeset_from(fallback),
    )